/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PuikAlert: typeof import('@prestashopcorp/puik-components')['PuikAlert']
    PuikAvatar: typeof import('@prestashopcorp/puik-components')['PuikAvatar']
    PuikBadge: typeof import('@prestashopcorp/puik-components')['PuikBadge']
    PuikButton: typeof import('@prestashopcorp/puik-components')['PuikButton']
    PuikButtonGroup: typeof import('@prestashopcorp/puik-components')['PuikButtonGroup']
    PuikCard: typeof import('@prestashopcorp/puik-components')['PuikCard']
    PuikChip: typeof import('@prestashopcorp/puik-components')['PuikChip']
    PuikIcon: typeof import('@prestashopcorp/puik-components')['PuikIcon']
    PuikLink: typeof import('@prestashopcorp/puik-components')['PuikLink']
    PuikSkeletonLoader: typeof import('@prestashopcorp/puik-components')['PuikSkeletonLoader']
    PuikSkeletonLoaderGroup: typeof import('@prestashopcorp/puik-components')['PuikSkeletonLoaderGroup']
    PuikSwitch: typeof import('@prestashopcorp/puik-components')['PuikSwitch']
    PuikTable: typeof import('@prestashopcorp/puik-components')['PuikTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestAlert: typeof import('./src/components/testAlert.vue')['default']
    TestAvatar: typeof import('./src/components/testAvatar.vue')['default']
    TestBadge: typeof import('./src/components/testBadge.vue')['default']
    TestBreadcrumb: typeof import('./src/components/testBreadcrumb.vue')['default']
    TestButton: typeof import('./src/components/testButton.vue')['default']
    TestChip: typeof import('./src/components/testChip.vue')['default']
    TestIcon: typeof import('./src/components/testIcon.vue')['default']
    TestNotificationBar: typeof import('./src/components/testNotificationBar.vue')['default']
    TestSkeleton: typeof import('./src/components/testSkeleton.vue')['default']
    TestSwitch: typeof import('./src/components/testSwitch.vue')['default']
    TestTable: typeof import('./src/components/testTable.vue')['default']
  }
}
